# https://github.com/jtdor/build-deb-action
# extra-build-deps overrides depends from control
# play with debchange --controlmaint
#     before-build-hook: 
#       cat /etc/os-release; 
#       git submodule update --init; 
#       make setup-golpe; 
#       debchange --controlmaint \
#         --local="+ci${{ github.run_id }}~git$(git rev-parse --short HEAD)" "CI build"
name: debian

on: [push, pull_request]

jobs:
  debian:
    runs-on: ubuntu-latest
    steps:
      - 
        name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - 
        name: build-deb-amd64
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=binary --no-sign
          extra-build-deps:  git g++ make pkg-config libtool ca-certificates libyaml-perl libtemplate-perl libregexp-grammars-perl libssl-dev zlib1g-dev liblmdb-dev libflatbuffers-dev libsecp256k1-dev libzstd-dev devscripts
          before-build-hook: cat /etc/os-release; git submodule update --init; make setup-golpe; 
          host-arch: amd64
      - 
        name: upload
        uses: actions/upload-artifact@v4
        with:
          path: debian/artifacts/
          name: debian_package

