# Execute tests on *BSD platforms. Does not produce wheels.
# Useful URLs:
# https://github.com/vmactions/freebsd-vm
# https://github.com/vmactions/openbsd-vm
# https://github.com/vmactions/netbsd-vm
#
name: freebsd-strfry
on: [ push, pull_request ]
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && github.sha || '' }}
  cancel-in-progress: true
jobs:
￼  ###
￼  #
￼  # FreeBSD build job
￼  #
￼  freebsd:
￼    runs-on: macos-latest
￼    steps:
￼    - uses: actions/checkout@v4
￼    - name: strfry test
￼      uses: vmactions/freebsd-vm@v0.0.7
￼      with:
￼        prepare: |
           pkg install -y gcc gmake cmake git perl5 openssl lmdb flatbuffers libuv libinotify zstr secp256k1 zlib-ng p5-Regexp-Grammars p5-Module-Install-Template p5-YAML
￼        run: |
            # git submodule update --init
            # gmake setup-golpe
            git checkout feature/freebsd-support-three
            git submodule update --init
            cd golpe
            git checkout feature/freebsd-support-three
            git submodule update --init
            cd external/uWebSockets
            git checkout feature/freebsd-support-three
            cd ../../../
            gmake
