# * manually applying safe.directory
#
# git config --global --add safe.directory /home/runner/work/strfry/strfry
# to avoid similar errors that may not be applicable if branches or submodules are not used
# https://stackoverflow.com/questions/72978485/git-submodule-update-failed-with-fatal-detected-dubious-ownership-in-repositor
#
# * release value is set to 13.2, remove to set to latest.
#
# * docs
# https://github.com/vmactions/freebsd-vm/blob/main/README.md
#
name: freebsd

on: [push, pull_request]

jobs:
  freebsd:
    runs-on: ubuntu-latest
    name: A job to build and run strfry in FreeBSD
    steps:
    - name: Checkout strfry
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create missing patch
      run: |
          cat <<EOF > missing-freebsd.patch
--- strfry.hoytech/golpe/external/uWebSockets/Makefile	2024-01-05 13:36:18.260089000 -0800
+++ strfry/golpe/external/uWebSockets/Makefile	2023-10-24 14:58:24.873358000 -0700
@@ -1,8 +1,8 @@
 W        = -Wall
-OPT      = -O2 -g
+OPT      = -O2 -g -I/usr/local/include
 STD      = -std=c++17
 CXXFLAGS = $(STD) $(OPT) $(W) -fPIC $(XCXXFLAGS)
-INCS     = -Isrc/
+INCS     = -Isrc/ -I/usr/local/include
 
 SRCS = src/Extensions.cpp src/Group.cpp src/Networking.cpp src/Hub.cpp src/Node.cpp src/WebSocket.cpp src/HTTPSocket.cpp src/Socket.cpp src/Epoll.cpp src/Room.cpp
 
--- strfry.hoytech/golpe/external/uWebSockets/src/Networking.h	2024-01-05 13:36:18.264054000 -0800
+++ strfry/golpe/external/uWebSockets/src/Networking.h	2023-10-24 14:58:24.873428000 -0700
@@ -16,6 +16,10 @@
 #include <endian.h>
 #endif
 
+#ifdef __FreeBSD__
+#include <sys/endian.h>
+#endif
+
 #ifdef __APPLE__
 #include <libkern/OSByteOrder.h>
 #define htobe64(x) OSSwapHostToBigInt64(x)
--- strfry.hoytech/golpe/rules.mk	2024-01-05 13:35:52.426935000 -0800
+++ strfry/golpe/rules.mk	2024-01-05 14:33:43.822237000 -0800
@@ -1,15 +1,34 @@
+ifeq ($(shell echo | gcc -E -dM - | grep -c __FreeBSD__),1)
+    __FreeBSD__ = 1
+endif
+
 APPS     ?=
 export APPS
 
 W        ?= -Wall
 OPT      ?= -O2 -g
 STD      ?= -std=c++20
+
+ifneq ($(origin __FreeBSD__), undefined)
+CXX      = g++
+CC       = cc
+MAKE     = gmake
+STD      += -stdlib=libc++
+endif
+
 CXXFLAGS += $(STD) $(OPT) $(W) -fPIC $(XCXXFLAGS) -DDOCOPT_HEADER_ONLY
 INCS     += -Iinclude -Ibuild -Isrc -Igolpe/external -Igolpe/external/lmdbxx/include -Igolpe/external/config/include -Igolpe/external/json/include -Igolpe/external/PEGTL/include -Igolpe/external/hoytech-cpp -Igolpe/external/docopt.cpp -Igolpe/external/loguru -Igolpe/external/parallel-hashmap
 LDLIBS   += golpe/external/uWebSockets/libuWS.a -ldl -lz -lcrypto -lssl -llmdb -pthread
 LDFLAGS  += -flto $(XLDFLAGS)
 SRCS    := golpe/logging.cpp build/main.cpp build/config.cpp $(wildcard src/*.cpp) $(wildcard $(foreach p,$(APPS),src/apps/$(p)/*.cpp))
 
+ifneq ($(origin __FreeBSD__), undefined)
+    INCS    += -I/usr/local/include  # Add FreeBSD-specific include paths
+    LDLIBS  += -linotify -lc++ -luv
+    NPROC = 2
+endif
+
+
 OBJS    := $(SRCS:.cpp=.o)
 DEPS    := $(SRCS:.cpp=.d)
 
@@ -25,7 +44,7 @@
 	$(CXX) $(OBJS) $(CMDOBJS) $(LDFLAGS) $(LDLIBS) -o $(BIN)
 
 golpe/external/uWebSockets/libuWS.a:
-	cd golpe/external/uWebSockets && make -j libuWS.a
+	cd golpe/external/uWebSockets && make -j$(NPROC) libuWS.a
 
 %.o : %.cpp build/golpe.h build/config.h build/defaultDb.h
 	$(CXX) $(CXXFLAGS) $(INCS) -MMD -MP -MT $@ -MF $*.d -c $< -o $@
 
EOF

    - name: Build strfry
      uses: vmactions/freebsd-vm@v1
      with:
        release: 13.2
        usesh: true
        prepare: |
          pkg install -y gcc gmake cmake git perl5 openssl lmdb flatbuffers libuv libinotify zstr secp256k1 zlib-ng p5-Regexp-Grammars p5-Module-Install-Template p5-YAML wget

        run: |
          # ownership workaround
          git config --global --add safe.directory /home/runner/work/strfry/strfry
          git config --local --name-only --get-regexp core.sshCommand
          git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"          
          git submodule update --init
          make setup-golpe

          patch -p1 < missing-freebsd.patch

          gmake
          if ! [ -f ./strfry ]; then
             echo "Strfry build failed."
             exit 1
          fi

          freebsd/build-pkg.sh

          # backgrounding does not return
          ./strfry info 
          freebsd-version

    - name: Verify strfry copy back
      run: |
          pkgfilename=`ls *.pkg`
          echo "pkgfilename=$pkgfilename" >> $GITHUB_ENV

    - name: Upload strfry
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.pkgfilename }}
        path: ${{ env.pkgfilename }}

