name: raspios-arm64-deb

on:
  push:

jobs:
  raspios-arm64-deb:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout strfry
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Build strfry
      uses: pguyot/arm-runner-action@HEAD
      with:
        base_image: raspios_lite_arm64:latest
        cpu: cortex-a53
        commands: |
          echo "Minimal"
          test `uname -m` = 'aarch64'
          ls
