name: ubuntu-docker-deb

on: [push, pull_request]

jobs:
  ubuntu-docker:
    runs-on: ubuntu-latest
    name: A job to build and run strfry Ubuntu using Docker

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build the Ubuntu lunar Docker image for strfry
      run: |
        docker build . --file ubuntu-lunar.Dockerfile --tag lunar/strfry
        
    - name: Run the Ubuntu lunar Docker image for strfry
      run: |
        docker images
        docker run -v /home/runner/work/strfry/strfry/strfry-db:/app/strfry-db \
                   -v /home/runner/work/strfry/strfry/strfry.conf:/app/strfry.conf \
                   -d lunar/strfry

    - name: Extract DEB artifact from the Docker container
      run: |
        CONTAINER_ID=$(docker ps -q --filter ancestor=lunar/strfry)
        echo $CONTAINER_ID
        docker ps
        docker exec –workdir /app -it lunar/strfry ls
        docker cp $CONTAINER_ID:/app/strfry-*.deb ./strfry.deb
        docker exec –workdir /app -it lunar/strfry ls

    - name: Upload Debian artifact
      uses: actions/upload-artifact@v2
      with:
        name: strfry-rpm
        path: ./strfry.rpm
