name: ubuntu

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    name: A job to build and run strfry on Ubuntu
    steps:
      - name: Checkout strfry
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build strfry
        run: |
          sudo apt update && sudo apt install -y --no-install-recommends \
          git g++ make pkg-config libtool ca-certificates \
          libyaml-perl libtemplate-perl libregexp-grammars-perl libssl-dev zlib1g-dev \
          liblmdb-dev libflatbuffers-dev libsecp256k1-dev libzstd-dev
          git submodule update --init
          make setup-golpe
          make -j4
          if ! [ -f ./strfry ]; then
             echo "Strfry build failed."
             exit 1
          fi

      - name: Package strfry
        run: |
          sudo apt-get install debhelper devscripts -y
          mk-build-deps --install --tool="${install_tool}" debian/control
          # Build the package
          dpkg-buildpackage --build=binary -us -uc
          # Output the filename
          cd ..
          filename=`ls *.deb | grep -v -- -dbgsym`
          dbgsym=`ls *.deb | grep -- -dbgsym`
          echo ::set-output name=filename::$filename
          echo ::set-output name=filename-dbgsym::$dbgsym
          # Move the built package into the Docker mounted workspace
          mv $filename $dbgsym workspace/
          # Set the install command to be used by mk-build-deps (use --yes for non-interactive)
          mv $filename $dbgsym workspace/

      - name: Upload strfry
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.build.outputs.filename }}
          path: ${{ steps.build.outputs.filename }}

      - name: Run strfry
        run: |
          cat /etc/os-release
          sudo ./strfry relay &

