name: ubuntu-docker

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Ubuntu Docker image
      run: docker build . --file ubuntu.Dockerfile --tag my-image-name:$(date +%s)
      
